---
- name: Jelastic Test Ansible Manifest!
  hosts: all
 
  tasks:
 
  - name: Create a marker test file
    shell: echo "this is a test file" > /root/jelastic-test

  - name: Wget is installed
    yum:
      name: 
        - wget
        - java-11-openjdk
      state: present
      update_cache: true
    become: true

