---
- name: Jelastic Test Ansible Manifest!
  hosts: all
 
  tasks:
 
  - name: Create a marker test file
    shell: echo "this is a test file" > /root/jelastic-test

  - name: Install few packages
    yum:
      name: 
        - wget
        - java-11-openjdk
      state: present
      update_cache: true
    become: true
    
  - name: Add John Lesley from Detroit test user
    user:
      name: johnlesley
      comment: John Lesley
      uid: 1099
      group: admin

